### ISSUE TITLE
[install] ClamAV database fails to update

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#484]
```
+/workdir/scripts/winesapos-install.sh:456> sudo -u root /root/.local/bin/cvd update
Traceback (most recent call last):
  File "/root/.local/bin/cvd", line 5, in <module>
    from cvdupdate.__main__ import cli
  File "/root/.local/lib/python3.10/site-packages/cvdupdate/__main__.py", line 42, in <module>
    from cvdupdate import auto_updater
  File "/root/.local/lib/python3.10/site-packages/cvdupdate/auto_updater.py", line 3, in <module>
    from cvdupdate.cvdupdate import CVDUpdate
  File "/root/.local/lib/python3.10/site-packages/cvdupdate/cvdupdate.py", line 28, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

https://github.com/LukeShortCloud/winesapOS/actions/runs/3194266663/jobs/5213670467

**Comment by LukeShortCloud** [comment]
A quick search online says that the "setuptools" Python package needs to be installed to fix this error.

**Comment by LukeShortCloud** [comment]
I confirmed with manual testing that installing the `python-setuptools` package fixes this issue.
